@BusinessLogicAPI_HostAddress = https://localhost:7080

POST {{BusinessLogicAPI_HostAddress}}/rules/validate
Content-Type: application/json
Accept: application/json

{
  "carrierId": 1,
  "featureName": "DrugValidation",
  "requestDate": "2025-01-15",
  "drugId": 123,
  "planId": 456
}

###

GET {{BusinessLogicAPI_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{BusinessLogicAPI_HostAddress}}/scalar
Accept: text/html

###
